/*
 * PainelConfiguracao.java
 *
 * Created on Jan 21, 2013, 3:47:54 PM
 */
package simuladorsemaforos;

/**
*Programa que simula o tráfego de veículos por um semáforo entre duas ruas que se cruzam e tem direção única
*@author Rogério de Paula Aguilar - rogeriodpaguilarbr@gmail.com
*
* os arquivos fontes estão com a codificação utf-8
* mais informações no arquivo leiame.txt
* OBS: esta classe é gerada pelo editor visual do netbeans e é criada apenas para posicionar os elementos
* na tela
* Para alterar o comportamento dos controles, alterar a classe PainelConfiguraçãoSub
*/
public class PainelConfiguracao extends javax.swing.JPanel {

    /** Creates new form PainelConfiguracao */
    public PainelConfiguracao() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        comboCores = new javax.swing.JComboBox();
        lblTempo = new javax.swing.JLabel();
        sliderTempoParaChegarAoSemaforo = new javax.swing.JSlider();
        chkAdicionarPistaEsquerdaDireita = new javax.swing.JCheckBox();
        chkAdicionarPistaCimaBaixo = new javax.swing.JCheckBox();
        cmdAdicionar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        cmdComecar = new javax.swing.JButton();
        cmdPreenchimentoAleatorio = new javax.swing.JButton();
        chkExibirImagens = new javax.swing.JCheckBox();
        chkExibirInformacoes = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPistaEsquerdaDireita = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaPistaCimaBaixo = new javax.swing.JTable();

        jLabel1.setText("jLabel1");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setMaximumSize(new java.awt.Dimension(380, 580));
        setMinimumSize(new java.awt.Dimension(380, 580));
        setLayout(null);

        jPanel3.setMaximumSize(new java.awt.Dimension(350, 580));
        jPanel3.setMinimumSize(new java.awt.Dimension(350, 580));
        jPanel3.setPreferredSize(new java.awt.Dimension(350, 628));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Carro"));
        jPanel4.setMaximumSize(new java.awt.Dimension(370, 179));
        jPanel4.setPreferredSize(new java.awt.Dimension(370, 179));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Cor:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        comboCores.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCores.setName("comboCores"); // NOI18N
        jPanel4.add(comboCores, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 120, 40));

        lblTempo.setText("Tempo (segundos):");
        jPanel4.add(lblTempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 220, -1));

        sliderTempoParaChegarAoSemaforo.setMajorTickSpacing(10);
        sliderTempoParaChegarAoSemaforo.setMaximum(30);
        sliderTempoParaChegarAoSemaforo.setMinimum(1);
        sliderTempoParaChegarAoSemaforo.setMinorTickSpacing(1);
        sliderTempoParaChegarAoSemaforo.setPaintTicks(true);
        sliderTempoParaChegarAoSemaforo.setValue(5);
        jPanel4.add(sliderTempoParaChegarAoSemaforo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 179, -1));

        chkAdicionarPistaEsquerdaDireita.setText("Adicionar na pista um (esquerda - direita)");
        chkAdicionarPistaEsquerdaDireita.setName("chkAdicionarNaPistaEsquerdaDireita"); // NOI18N
        jPanel4.add(chkAdicionarPistaEsquerdaDireita, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 320, -1));

        chkAdicionarPistaCimaBaixo.setText("Adicionar na pista dois (cima - baixo)");
        chkAdicionarPistaCimaBaixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAdicionarPistaCimaBaixoActionPerformed(evt);
            }
        });
        jPanel4.add(chkAdicionarPistaCimaBaixo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 320, -1));

        cmdAdicionar.setText("Adicionar");
        jPanel4.add(cmdAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 100, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Simulação"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdComecar.setText("Começar");
        cmdComecar.setName("cmdComecar"); // NOI18N
        cmdComecar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdComecarActionPerformed(evt);
            }
        });
        jPanel5.add(cmdComecar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        cmdPreenchimentoAleatorio.setText("Preenchimento Aleatório");
        jPanel5.add(cmdPreenchimentoAleatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        chkExibirImagens.setSelected(true);
        chkExibirImagens.setText("Exibir Imagens");
        chkExibirImagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkExibirImagensActionPerformed(evt);
            }
        });
        jPanel5.add(chkExibirImagens, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        chkExibirInformacoes.setSelected(true);
        chkExibirInformacoes.setText("Exibir Informações");
        chkExibirInformacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkExibirInformacoesActionPerformed(evt);
            }
        });
        jPanel5.add(chkExibirInformacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Pista Um (Esquerda - Direita):"));
        jPanel7.setPreferredSize(new java.awt.Dimension(370, 130));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(375, 100));

        tabelaPistaEsquerdaDireita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaPistaEsquerdaDireita);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 320, -1));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Pista Dois (Cima - Baixo):"));
        jPanel8.setPreferredSize(new java.awt.Dimension(370, 130));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane4.setPreferredSize(new java.awt.Dimension(375, 100));

        tabelaPistaCimaBaixo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tabelaPistaCimaBaixo);

        jPanel8.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 320, 90));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );

        add(jPanel3);
        jPanel3.setBounds(10, 0, 370, 628);
    }// </editor-fold>//GEN-END:initComponents

    private void chkAdicionarPistaCimaBaixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAdicionarPistaCimaBaixoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAdicionarPistaCimaBaixoActionPerformed

    private void cmdComecarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdComecarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdComecarActionPerformed

    private void chkExibirImagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkExibirImagensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkExibirImagensActionPerformed

    private void chkExibirInformacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkExibirInformacoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkExibirInformacoesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JCheckBox chkAdicionarPistaCimaBaixo;
    protected javax.swing.JCheckBox chkAdicionarPistaEsquerdaDireita;
    protected javax.swing.JCheckBox chkExibirImagens;
    protected javax.swing.JCheckBox chkExibirInformacoes;
    protected javax.swing.JButton cmdAdicionar;
    protected javax.swing.JButton cmdComecar;
    protected javax.swing.JButton cmdPreenchimentoAleatorio;
    protected javax.swing.JComboBox comboCores;
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JLabel jLabel4;
    protected javax.swing.JPanel jPanel3;
    protected javax.swing.JPanel jPanel4;
    protected javax.swing.JPanel jPanel5;
    protected javax.swing.JPanel jPanel7;
    protected javax.swing.JPanel jPanel8;
    protected javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JScrollPane jScrollPane2;
    protected javax.swing.JScrollPane jScrollPane4;
    protected javax.swing.JTable jTable2;
    protected javax.swing.JLabel lblTempo;
    protected javax.swing.JSlider sliderTempoParaChegarAoSemaforo;
    protected javax.swing.JTable tabelaPistaCimaBaixo;
    protected javax.swing.JTable tabelaPistaEsquerdaDireita;
    // End of variables declaration//GEN-END:variables
}
